services:
   db:
     container_name: postgres
     image: postgres
     enviromwent:
       POSTGRES_USER: amigoscode
       POSTGRES_PASSWORD: password
       PGDATA: /data/postgres
       volumes:
         -db:/data/postgres
       port:
         - "5332:5432"
       networks:
         -db
       restart: unless-stopped

       networks:
         db:
           driver: bridge

        volumes:
          db:
